[and]
signature = ['bool', 'bool']
examples = [[true, false], [true, true], [false, false], [false, true]]

[andc]
signature = ['bool', 'bool']
examples = [[true, false], [true, true], [false, false], [false, true]]